### ISSUE TITLE
Compilation errors with Visual Studio 14 2015 + FLAC

### ISSUE THREAD

**Issue by mattetti** [teragonaudio/MrsWatson#222] opened 2015-12-04 04:54 UTC
```
#ifdef snprintf
    #error Macro definition of snprintf conflicts with Standard Library 
             function declaration
#endif
```

Probably similar problem then mentioned here: http://stackoverflow.com/questions/27754492/vs-2015-compiling-cocos2d-x-3-3-error-fatal-error-c1189-error-macro-definiti

**Comment by JC-Morph** [comment] 2016-01-18 02:26
Hi

The offending definition is found in master/source/base/Types.h
The following line must be removed:

`#define snprintf _snprintf`


Additionally I found that, at present, it is necessary to remove all references to `showVst2xEditor` that can be found in master/source/plugin/PluginVst2x.cpp

This is most likely because this feature has not been fully implemented yet.

I have already made a branch of the changes described above [here](https://github.com/JC-Morph/MrsWatson/tree/buildfix-showVstEditor).

Kind regards,
JC

**Comment by dts350z** [comment] 2016-02-06 22:59
When I compile the branch (visual studio 2015), ,described above, when loading a 32bit vst I get:

C:\Users\gnewell\Downloads\MrsWatson-buildfix-showVstEditor\build\main\Debug>mrswatson.exe -p Maxwell_Smart --parameter 2,0.875  -i "C:\Users\gnewell\Google Drive\01 Antissa-mch.wav" -o "C:\Users\gnewell\Google Drive\01 Antissa-mch-out .wav"
- 00000000 000000 MrsWatson version 0.9.8 initialized, build 20160206
- 00000000 000015 Setting 6 channels
- 00000000 000015 Setting sample rate to 44100Hz
- 00000000 000015 Setting 6 channels
- 00000000 000015 Setting sample rate to 44100Hz
- 00000000 000015 Plugin 'Maxwell_Smart' is of type VST2.x
- 00000000 000015 Opening VST2.x plugin 'Maxwell_Smart'
E 00000000 000015 Could not open library, wrong architecture
E 00000000 000015 Plugin 'Maxwell_Smart' could not be opened
E 00000000 000015 Plugin 'Maxwell_Smart' could not be added to the chain
E 00000000 000015 Plugin chain could not be constructed, exiting

Notice that I am running the 32 bit mrswatson.exe

This didn't happen with the windows binary version 0.9.7, build 20140125

Am I doing something wrong?

**Comment by dts350z** [comment] 2016-02-07 17:13
Also, even with internal plugins 0.98 compiled with VS 2015 doesn't work for 6ch. 16 bit wav files (which 0.97 binary did). Heap corruption:

C:\Users\Glenn\Google Drive\MrsWatson-master\build\main\Debug>mrswatson.exe -p mrs_passthru -i "C:\Users\Glenn\Google Drive\01 Antissa-mch.wav" -o "C:\Users\Glenn\Google Drive\01 Antissa-mch-out.wav"
- 00000000 000000 MrsWatson version 0.9.8 initialized, build 20160206
- 00000000 000000 Setting 6 channels
- 00000000 000000 Setting sample rate to 44100Hz
- 00000000 000000 Setting 6 channels
- 00000000 000000 Setting sample rate to 44100Hz
W 00000000 000000 Location 'C:\VstPlugins' is not a valid directory
W 00000000 000000 Location 'C:\Program Files\VstPlugIns' is not a valid directory
W 00000000 000000 Location 'C:\Program Files\Common Files\VstPlugIns' is not a valid directory
W 00000000 000016 Location 'C:\Program Files\Steinberg\VstPlugIns' is not a valid directory
- 00000000 000016 Plugin 'mrs_passthru' is an internal plugin
- 00000000 000016 Starting processing input source

Then crash with heap corruption.

Also, even though all the flac, etc. stuff is in there, it complains about 24 bit files (wav or flac).

**Comment by dts350z** [comment] 2016-02-07 18:02
It would appear the snprintf are still present when building with audiofile.

**Comment by dts350z** [comment] 2016-02-07 20:03
OK after hours of work I got flac and audiofile projects to compile without errors with Visual Studio 2015.

Now, however, the mrswatson project has 18 link errors, similar to this:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol __imp_FLAC__stream_decoder_process_until_end_of_metadata referenced in function "public: virtual enum status __cdecl FLACFile::readInit(struct _AFfilesetup *)" (?readInit@FLACFile@@UEAA?AW4status@@PEAU_AFfilesetup@@@Z)	mrswatson	C:\Users\gnewell\Downloads\MrsWatson-buildfix-showVstEditor\build\main\audiofile.lib(FLACFile.obj)	1	

and I'm stuck. Any ideas?

audofile and flac lib files are built and found in the project properties.

**Comment by nikreiman** [comment] 2016-02-19 10:21
I just pushed a few fixes to `master`, I can now compile on VS 2015 without any warnings/errors both with and without audiofile. There are some issues building with flac support enabled, I'm guessing that the project needs to bump the submodule, and also probably to add C++11 support when building this lib. Anyways, without flac, I can run the test suite with no errors and no crashes, including the integration tests (which fork a separate mrswatson.exe instance). As such, I've edited the issue name to reflect that.

For me, the 24-bit AIFF/WAVE tests run fine. Are you still getting heap corruption with them @dts350z ?

**Comment by dts350z** [comment] 2016-02-20 06:39
The problems I am having now are:

1) VS Studio 2015 makes 64 bit exes for both w64 and 32 bit projects (leading to "wrong architecture" with mrswatson and 32bit VSTs. I can get around this with a bunch of effort in visual studio but I would think you would want it to work out of the box.

2) The output file length does not equal the input file length, even for mrs_passthru plugin. Output file (6 ch) has 348 more samples than input file. These are 24 bit std wave files.

**Comment by dts350z** [comment] 2016-02-20 07:37
flac and w64 support are also important

**Comment by nre-ableton** [comment] 2016-06-30 12:18
@dts350z Regarding your first point, I have pushed a fix to master that corrects this. Now, CMake only generates binaries for the configured architecture (it's not possible for VS to build both a 32 and 64-bit binary in one build). I'll investigate the flac stuff as well.

**Comment by nikreiman** [comment] 2016-07-01 13:21
As of commit 59c2e95, MrsWatson now builds on Windows with FLAC enabled, for both 32/64-bit builds. Regarding the output file length with 24-bit wave files, I've moved your comments into #206, since these bugs are likely caused by the same issue.

**Closed by nikreiman** 2016-07-01 13:21 UTC
