### ISSUE TITLE
Read Event Midi

### ISSUE THREAD

**Issue by lumy** [teragonaudio/MrsWatson#230] opened 2016-03-31 15:32 UTC
Hello,

I've bee running your mrsWatson and got that message:

```
    Failed reading MIDI events
```

You can find attached the midi file used and the report bug.

[MrsWatson-Report-Thu-Mar-31-15-53-13-2016.txt](https://github.com/teragonaudio/MrsWatson/files/197957/MrsWatson-Report-Thu-Mar-31-15-53-13-2016.txt)
[480a510323d296ca021c45eb0c33b6d61ac852c651c7c93649609e673552f7fe.mid.zip](https://github.com/teragonaudio/MrsWatson/files/197962/480a510323d296ca021c45eb0c33b6d61ac852c651c7c93649609e673552f7fe.mid.zip)

**Comment by nikreiman** [comment] 2016-10-30 14:03
Hi @lumy, thanks for the report. I'll look into this and see if I can reproduce.

**Comment by nikreiman** [comment] 2016-10-30 15:01
The reason the MIDI file can't be read is that it is type 1. The current stable version doesn't have very good error logging for this.

MrsWatson currently only supports type 0 files, but type 1 support is planned. Closing as duplicate, please follow issue #24.

**Closed by nikreiman** 2016-10-30 15:01 UTC
